### ISSUE TITLE
Error: template: index.html:23:65: executing "index.html" 

### ISSUE THREAD

**Issue by xunil75** [GeniusDex/racce#1]
Hi, first of all I would like to thank you for this stats tool I really like it.

Everything was working fine until yesterday and I bellieve I did nothing wrong besides stoping the server and changing track. The server is running and I can see and join the server within ACC, however I have this error on the webinterface:

`template: index.html:23:65: executing "index.html" at <.TrackName>: nil pointer evaluating *accdata.Track.Name`

I can still login into the Admin page to stop/start the server but other then that there's nothing I can see.

Can you help?

Regards

**Comment by GeniusDex** [comment]
This is probably caused by a results file having unexpected contents. You can try which file is causing it by moving some of the json files in/out of the results directory and restarting the server until the index works again.

If you found the file which causes the problem, can you share it for analysis?

**Comment by xunil75** [comment]
ok, I will let you know as soon I get home. Thanks!

**Comment by xunil75** [comment]
Hi again, so the Problem is now solved. However it was not a result file but the event.json inside the cfg folder. The problem startet when I changed the track from monza_2019 to nurburgring_2019. nurburgring_2019 causes the problem stated above. I did not try other tracks yet but I'll let you check on your side first if you have the same behavior like I do.

Let me know, I'm curious :)

**Comment by GeniusDex** [comment]
I couldn't spell Nurburgring correctly, it's fixed :)
