### ISSUE TITLE
Unable to drill down when using X-Forwarded-Prefix request header

### ISSUE THREAD

**Issue by dichternebel** [GeniusDex/racce#2]
First of all: racce is awesome! I'm loving it.

Now I wanted to have a second instance running on the same VM using a path called "/practice" by adding the X-Forwarded-Prefix request header. racce is respecting that and is changing the links to the events and also to the players on the index page. But then when I want to drill down into an event or player I'm stuck at the index page.
I also noticed that I get a 404 for the styles.css: The URL to load the stylesheet file was also enriched with the prefix. That's definetly a bug.

Help is very much apprechiated!

**Comment by geniusdex** [comment]
Can you share your configuration.json, and the configuration of your webserver that you use for this? Be sure to remove any passwords from the files before posting them here.

Thanks for the nice words!

**Comment by dichternebel** [comment]
Looking at the reverse proxy configuration I noticed that I did a misconfiguration when rewriting the URL... got it working now! Thanks a lot again for making racce!
